version: '2'
services:    
  db:
    container_name: sendgridproxy-mysql
    image: mysql:5.7
    restart: always
    volumes:
      - sendgridproxy-db-data:/var/lib/mysql
      - sendgridproxy-db-config:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sendgridproxy
      MYSQL_DATABASE: sendgridproxy
      MYSQL_USER: sendgridproxy
      MYSQL_PASSWORD: sendgridproxy         
      TZ: Europe/Warsaw
    ports:
      - 3306:3306
    networks:
      - sendgridproxy-network
    #mem_limit: 2G
    #memswap_limit: 0
    #mem_reservation: 1G
  php:
    build: .
    container_name: sendgridproxy-php
    hostname: sendgridproxy-prod
    environment:
      DBCONNECTIONSTRING: mysql:host=db
      DBSCHEMA: sendgridproxy
      DBUSER: sendgridproxy
      DBPASS: sendgridproxy
      LOG4PHPCONFIGFILE: /var/www/config/loggerConfig.xml  
      ISSUERREALMS: https://auth.piechocki.info/auth/realms/interior
      VERSION: 1.0.0    
      TZ: Europe/Warsaw
      GELF_HOST: graylog.piechocki.company
      GELF_PORT: 12201
      LOG_LEVEL: 100
    ports:
      - '80:80'
    restart: always
    volumes:
      - sendgridproxy-app-log:/var/www/log
      - sendgridproxy-app-config:/var/www/config
    networks:
      - sendgridproxy-network
    depends_on:
      - db
networks:
  sendgridproxy-network:
volumes: 
  sendgridproxy-app-log:  
  sendgridproxy-app-config:   
  sendgridproxy-db-data:
  sendgridproxy-db-config: 