version: '3'
services:
  db:
    container_name: requpero-mysql
    image: mysql:8.0
    restart: always
    volumes:
      - requpero-db-data:/var/lib/mysql
      - requpero-db-config:/etc/mysql
      - requpero-db-mysql-config:/var/lib/mysql-files
    environment:
      MYSQL_DATABASE: requpero
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Europe/Warsaw
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 60s
    ports:
      - 3306:3306
    networks:
      - requpero-network
  php:
    build: .
    container_name: requpero-php
    hostname: requpero-test
    environment:
      DBCONNECTIONSTRING: mysql:host=db
      DBSCHEMA: requpero
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
      ISSUERREALMS: https://auth.rubycon.info/auth/realms/interior
      VERSION: 1.0.0
      TZ: Europe/Warsaw
      GELF_HOST: graylog.rubycon.info
      GELF_PORT: 12201
      LOG_LEVEL: DEBUG
      LOG_FILE: ""
      AUTH_CLIENT_ID: "requpero"
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
    healthcheck:
      test: [ "CMD", "curl","-f","http://localhost/api.v1/health" ]
      timeout: 5s
      retries: 3
      interval: 60s
    ports:
      - '80:80'
    restart: always
    networks:
      - requpero-network
    depends_on:
      - db
networks:
  requpero-network:
volumes:
  requpero-db-data:
  requpero-db-config:
  requpero-db-mysql-config: