version: '3'
services:
  db:
    container_name: template-project-mysql
    image: mysql:8.0
    restart: always
    volumes:
      - template-project-db-data:/var/lib/mysql
      - template-project-db-config:/etc/mysql
      - template-project-db-mysql-config:/var/lib/mysql-files
    environment:
      MYSQL_DATABASE: template-project
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Europe/Warsaw
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 60s
    ports:
      - 3306:3306
    networks:
      - template-project-network
  php:
    build: .
    container_name: template-project-php
    hostname: template-project-prod
    environment:
      DBCONNECTIONSTRING: mysql:host=db
      DBSCHEMA: template-project
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
      ISSUERREALMS: https://auth.piechocki.company/auth/realms/interior
      VERSION: 1.0.0
      TZ: Europe/Warsaw
      GELF_HOST: graylog.piechocki.company
      GELF_PORT: 12201
      LOG_LEVEL: DEBUG
      LOG_FILE: ""
      AUTH_CLIENT_ID: "project"
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
    healthcheck:
      test: [ "CMD", "curl","-f","http://localhost/api.v1/health" ]
      timeout: 5s
      retries: 3
      interval: 60s
    ports:
      - '80:80'
    restart: always
    networks:
      - template-project-network
    depends_on:
      - db
networks:
  template-project-network:
volumes:
  template-project-db-data:
  template-project-db-config:
  template-project-db-mysql-config: 