version: '2'
services:    
  db:
    container_name: template-project-mysql
    image: mysql:8.0
    restart: always
    volumes:
      - template-project-db-data:/var/lib/mysql
      - template-project-db-config:/etc/mysql
      - template-project-db-mysql-config:/var/lib/mysql-files
    environment:
      MYSQL_DATABASE: transference
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}     
      TZ: Europe/Warsaw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    networks:
      - template-project-network
    mem_limit: 2G
    memswap_limit: 0
    mem_reservation: 1G
  php:
    build: .
    container_name: template-project-php
    hostname: template-project-test
    environment:
      DBCONNECTIONSTRING: mysql:host=db
      DBSCHEMA: template-project
      DBUSER: ${MYSQL_USER}
      DBPASS: ${MYSQL_PASSWORD}
      ISSUERREALMS: https://auth.rubycon.info/auth/realms/interior
      VERSION: 1.0.0    
      TZ: Europe/Warsaw
      GELF_HOST: graylog.rubycon.info
      GELF_PORT: 12201
      LOG_LEVEL: 100
      LOG_FILE: ""
      AUTH_CLIENT_ID: "project"
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost/api.v1/health"]
      timeout: 5s
      retries: 3
    ports:
      - '80:80'
    restart: always
    networks:
      - template-project-network
    depends_on:
      - db
networks:
    template-project-network:
volumes: 
  template-project-db-data:
  template-project-db-config: 
  template-project-mysql-config: 